### PR TITLE
Yvonne-ul6u45p-hw3-attempt2

### PR DESCRIPTION
**Pull request by Yvonne-ul6u45p**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by jamie212** [comment]
Please do not modify anything outside of your folder (validate.py). After correcting, please reply to this comment.

**Comment by Yvonne-ul6u45p** [comment]
> Please do not modify anything outside of your folder (validate.py). After correcting, please reply to this comment.

I have fixed it. Sorry for my carelessness.

**Comment by Yvonne-ul6u45p** [comment]
@jamie212 
> Please do not modify anything outside of your folder (validate.py). After correcting, please reply to this comment.

I have fixed it, please check it again. Sorry for my carelessness.

**Comment by jamie212** [comment]
> @jamie212
> 
> > Please do not modify anything outside of your folder (validate.py). After correcting, please reply to this comment.
> 
> I have fixed it, please check it again. Sorry for my carelessness.

截圖 2023-11-27 下午7 23 12
Sorry for the late reply. It seems that you have still made changes to things outside your folder. Please check again, you should only be able to modify files in hw3/Yvonne-ul6u45p.

**Comment by Yvonne-ul6u45p** [comment]
Truly sorry for that, and sorry for accidentally closing this PR. I have fixed it again.

Here are my steps.
1. git clone https://github.com/yungyuc/nsdhw_23au.git
2. git reset --hard fa66c187172ff488f968080488e3caab2fc13515 (to the commit "[hw3] Add homework3")
3. copy directory `Yvonne-ul6u45p` to the path `nsdhw_23au/hw3`
4. push to branch `Yvonne-ul6u45p-hw3-attempt2` of my repository
5. Pull requests

Here is the "Files changed" page of this PR.
image

If this still doesn't work, could you please give me some advice? Thanks for your efforts.

> > @jamie212
> > > Please do not modify anything outside of your folder (validate.py). After correcting, please reply to this comment.
> > 
> > 
> > I have fixed it, please check it again. Sorry for my carelessness.
> 
> 截圖 2023-11-27 下午7 23 12 Sorry for the late reply. It seems that you have still made changes to things outside your folder. Please check again, you should only be able to modify files in hw3/Yvonne-ul6u45p.

**Comment by jamie212** [comment]
> Truly sorry for that, and sorry for accidentally closing this PR. I have fixed it again.
> 
> Here are my steps.
> 
> 1. git clone https://github.com/yungyuc/nsdhw_23au.git
> 2. git reset --hard [fa66c18](https://github.com/yungyuc/nsdhw_23au/commit/fa66c187172ff488f968080488e3caab2fc13515) (to the commit "[hw3] Add homework3")
> 3. copy directory `Yvonne-ul6u45p` to the path `nsdhw_23au/hw3`
> 4. push to branch `Yvonne-ul6u45p-hw3-attempt2` of my repository
> 5. Pull requests
> 
> Here is the "Files changed" page of this PR. image
> 
> If this still doesn't work, could you please give me some advice? Thanks for your efforts.
> 
> > > @jamie212
> > > > Please do not modify anything outside of your folder (validate.py). After correcting, please reply to this comment.
> > > 
> > > 
> > > I have fixed it, please check it again. Sorry for my carelessness.
> > 
> > 
> > 截圖 2023-11-27 下午7 23 12 Sorry for the late reply. It seems that you have still made changes to things outside your folder. Please check again, you should only be able to modify files in hw3/Yvonne-ul6u45p.

It works, thanks!

**Pull request merged**
